<?= $this->partial('/section/jumbotron.phtml', array('title'=> $this->title)); ?>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="well">
                    <p class="lead text-center"><?= $this->translate($this->description); ?> </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $this->body; ?>
            </div>
            <div class="col-md-6">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <?= $this->form ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>