<?php IF (count($this->articles)) { ?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?= $this->translate('my blog') ?></h3>
    </div>
    <div class="panel-body">
        <?= $this->partial('/blog/row/thumbnails.phtml', array('articles' => $this->articles)); ?>
    </div>

    <div class="panel-footer">
        <a class="btn btn-outline btn-sm"
           href="<?php echo $this->url(array(), 'blog'); ?>"
           role="button">
            <?= $this->translate('Learn more') ?>
            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </a>
    </div>
</div>

<?php } ?>