<?php IF (count($this->products)) { ?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?= $this->translate('My products') ?></h3>
    </div>

    <div class="panel-body">

        <?= $this->partial('/blog/row/thumbnails.phtml', array('products' => $this->products)); ?>

    </div>

    <div class="panel-footer">
        <a class="btn btn-lg btn-outline"
           href="<?php echo $this->url(array(), 'gallery-index'); ?>"
           role="button">
            <?= $this->translate('Learn more') ?>
            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </a>
    </div>
</div>

<?php } ?>