<?php IF ($this->articles): ?>

    <div class="row">
        <?php FOREACH ($this->articles as $key => $article): ?>

            <div class="col-sm-6 col-md-4 col-lg-3">

                <?= $this->partial('/blog/row/thumbnail.phtml', array('article' => $article)); ?>

            </div>
            <?= $this->partial('/bootstrap/clearfix4.phtml', array('key' => $key)); ?>

        <?php ENDFOREACH; ?>
    </div>

<?php ENDIF; ?>
