<?= $this->partial('/section/jumbotron.phtml', array('title'=> $this->title, 'description'=>$this->description)); ?>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('/gallery/row/gallery-admin-panel.phtml'); ?>
            </div>
        </div>
        <div class="row">
            <?= $this->partial('gallery/row/galleries.phtml', array('galleries' => $this->records) ); ?>
        </div>
    </div>
</div>